version: '3.0'
services:
  ja2mqtt:
    container_name: ja2mqtt
    image: tomvit/ja2mqtt:latest
    depends_on:
      - mqtt-broker
  mqtt-broker:
    container_name: mqtt-broker
    volumes:
      - ./mqtt-config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    image: eclipse-mosquitto:latest
