name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout code
      - uses: crazy-max/ghaction-docker-buildx@v1
        name: install buildx
        id: buildx        
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin          
      - name: build the image
        run: |
          cd docker && docker buildx build \
          --tag tomvit/ja2mqtt:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
