name: buildx-image

on:
  push:
    branches: [ "master" ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Build Python package
        run: |
          python -m pip install --upgrade pip
          if [ -f bin/requirements.txt ]; then pip install -r bin/requirements.txt; fi
          rm -fr dist/*
          python3 setup.py egg_info sdist
          export version=$(egrep -o "__version__ = \".+\"" ja2mqtt/__init__.py | awk '{print $3}')
          mkdir -p docker/files
          cp dist/*.tar.gz docker/files
          cp config/sample-config.yaml docker/files
          cp config/ja2mqtt.yaml docker/files
          echo "::set-env name=version::$version"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "docker"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tomvit/ja2mqtt:latest, tomvit/ja2mqtt:${version}
